PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "schema_migrations" ("version" varchar NOT NULL);
INSERT INTO "schema_migrations" VALUES('20170213104520');
CREATE TABLE "companies" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "description" text, "income" integer(8), "employee_amount" integer(8), "address" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
INSERT INTO "companies" VALUES(1,'Apple','amerykańska korporacja zajmująca się projektowaniem i produkcją elektroniki użytkowej, oprogramowania i komputerów osobistych z siedzibą w Cupertino w Kalifornii. Założona przez Steve’a Wozniaka – projektanta, Steve’a Jobsa i Ronalda Wayne’a. Produkty spółki to m.in.: komputery Mac, iPod, iPhone, iPad, iWatch. Oprogramowanie Apple obejmuje system operacyjny macOS, przeglądarkę multimediów iTunes, pakiet oprogramowania multimedialnego i kreatywności iLife, pakiet oprogramowania biurowego iWork, profesjonalny pakiet fotografii Aperture, pakiet profesjonalnych rozwiązań wideo Final Cut Studio oraz zestaw narzędzi audio Logic Studio. Od stycznia 2010 roku firma działa poprzez 284 własnych sklepów detalicznych w dziesięciu krajach oraz za pośrednictwem sklepu internetowego sprzedającego zarówno sprzęt, jak i oprogramowanie.',215000000000,150000,'1 Infinite Loop','2017-02-21 06:42:38.557695','2017-02-21 12:47:12.034532');
INSERT INTO "companies" VALUES(2,'Microsoft','edno z największych na świecie przedsiębiorstw z branży technologii informacyjnych[4]. Najbardziej znane jako producent systemów operacyjnych MS-DOS, Microsoft Windows i oprogramowania biurowego Microsoft Office. Spółka publiczna z siedzibą w Redmond w stanie Waszyngton. Założona w 1975 roku przez Billa Gatesa i Paula Allena. W 2012 roku przedsiębiorstwo posiadało 10 000 patentów. Przeciętne wynagrodzenie pracowników to 106 tys. dolarów rocznie[5]. W 2014 roku prezesem przedsiębiorstwa został Satya Nadella, który zastąpił na tym stanowisku Steve’a Ballmera[6].',88000000000,128000,'11 Times Square 
','2017-02-21 06:47:15.565348','2017-02-21 12:45:04.685554');
INSERT INTO "companies" VALUES(3,'Tesla Motors','amerykańskie przedsiębiorstwo motoryzacyjne produkujące osobowe sportowe samochody elektryczne założone w lipcu 2003 roku przez Martina Eberharda, Marca Tarpenninga, JB Straubela oraz Iana Wrighta. W lutym 2004 prezesem rady nadzorczej Tesla Motors został Elon Musk, który później (w październiku 2008) został prezesem firmy.

Od 2003 do 2008 roku trwały prace nad wprowadzeniem do produkcji pierwszego samochodu marki Tesla o nazwie Roadster. Auto powstało we współpracy z Lotus Cars. Sylwetka auta zbliżona jest do Lotusa Elise oraz Europa. Pojazd wprowadzono do produkcji w 2008 roku. Rok później zaprezentowano prototyp 7-osobowego liftbacka segmentu E o zasięgu na jednym ładowaniu 300 mil oraz sportowych osiągach. Produkcja pojazdu rozpoczęła się w czerwcu 2012 roku pod nazwą Model S. Pod koniec 2014 roku do produkcji wszedł wariant z dwoma silnikami elektrycznymi, pozwalający na osiągnięcie 100 km/h w 3,2 s. Każdy produkowany od tamtego momentu pojazd otrzymał system aktywnej prewencji kolizji oraz możliwość dokupienia systemu Autopilot.

29 września 2015 roku odbyła się prezentacja oraz wręczenie pierwszych kluczyków do nowego Modelu X, który jest siedmioosobowym crossoverem. 31 marca 2016 został zaprezentowany Model 3. Do 31 stycznia 2016 przedsiębiorstwo funkcjonowało pod firmą Tesla Motors.',4000000,120000,'Palo Alto','2017-02-21 06:48:26.896163','2017-02-21 06:51:39.610058');
INSERT INTO "companies" VALUES(4,'Example Technology','Example Technology to firma zajmująca się obróbką płyt chodnikowych. Od 1850 roku pracuje nad zmianą płyt chodnikowych na winylowe, aby przechodnie mogli słuchać twórczość Abby bez przeszkód. Uznawana za najmniej przydatną firmę w historii',100,1,'New York, Elon Musk st.','2017-02-21 06:55:32.264218','2017-02-21 06:55:32.264218');
INSERT INTO "companies" VALUES(5,'CD Projekt Red','CD Projekt jest spółką notowaną na Giełdzie Papierów Wartościowych w Warszawie. Jej główna działalność obejmuje produkcję gier komputerowych, jak również, poprzez spółki zależne, cyfrową dystrybucję programów i filmów innych twórców. Studio deweloperskie CD Projekt RED, będące od października 2011 roku prawnie częścią spółki, zajmuje się przede wszystkim produkcją gier opartych na serii powieści o wiedźminie Andrzeja Sapkowskiego.',175000000,500,'ul. Jagiellońska 74, budynek E, Warszawa','2017-02-21 07:17:38.662393','2017-02-21 12:37:04.400364');
INSERT INTO "companies" VALUES(7,'Space X','amerykańskie przedsiębiorstwo przemysłu kosmicznego, założone w roku 2002. Jego celem jest budowa silników rakietowych i rakiet nośnych oraz statków kosmicznych, w tym także załogowych. Kluczem do osiągnięcia sukcesu ma być znaczne zmniejszenie kosztów wynoszenia ładunku na orbitę. Przede wszystkim, SpaceX projektuje i buduje serię rakiet orbitalnych Falcon i statków kosmicznych Dragon.

Siedziba, montownia rakiet i biuro projektowe znajdują się w Hawthorne (hrabstwo Los Angeles) w Kalifornii. Silniki i inne duże elementy testowane są w McGregor w stanie Teksas. Ponadto firma posiada kilka biur regionalnych na terenie USA, a w styczniu 2015 r. ogłoszono plan utworzenia w Redmond w stanie Waszyngton biura projektowego na potrzeby planowanej produkcji satelitów telekomunikacyjnych.',1000000000,5000,'Hawthorne, California','2017-02-21 07:23:19.510703','2017-02-21 07:40:46.773480');
INSERT INTO "companies" VALUES(8,'Piotr i Paweł','jedna z największych w Polsce sieci supermarketów[2], stworzona przez Eleonorę Woś i jej synów, Piotra i Pawła.

Według stanu na 24 października 2016 r. sieć miała 138 sklepów w Polsce[3]. Od 2003 prowadzi ponadto sprzedaż w internecie[1], obecnie dostępną w całej Polsce. Obrót sieci w 2015 wyniósł 2,123 mld złotych',424000000,4000,'Druskienicka 12, 60-476 Poznań','2017-02-21 12:36:22.178332','2017-02-21 12:36:22.178332');
INSERT INTO "companies" VALUES(9,'PKN Orlen','polski koncern paliwowo-energetyczny, lider wśród przedsiębiorstw petrochemicznych w Europie środkowo-wschodniej. Jedyny koncern w Polsce zajmujący się produkcją polimerów oraz monomerów. Główny producent produktów petrochemicznych w Czechach. Obecnie zatrudniający ponad 20 000 pracowników[4].

Właściciel sześciu rafinerii: w Płocku, Trzebini, Jedliczu na terenie Polski, w Litvínovie i Kralupach na terenie Czech oraz w Możejkach na Litwie. Łączne moce przerobowe rafinerii w 2015 r. wyniosły 35,2 GWe (16,2 GWe obiekty w Polsce, 8,7 GWe w Czechach i 10,2 GWe na Litwie)[5]. W 2015 r. wykorzystanie mocy przerobowych wyniosło ogółem 90%. Jako jedyne polskie przedsiębiorstwo notowane w rankingu Fortune 500 (297 pozycja, największym przedsiębiorstwem na świecie został brytyjsko – holenderski Shell)',22000000000,25000,'Ul. Bielańska 12 00-085 Warszawa','2017-02-21 12:41:34.448177','2017-02-21 12:41:34.448177');
INSERT INTO "companies" VALUES(10,'Grupa Maspex','polski koncern spożywczy[7] z siedzibą w Wadowicach, będący jednym z największych producentów żywności w Europie Środkowo-Wschodniej. Grupę zapoczątkowało przedsiębiorstwo Maspex powstałe w 1990 roku, zajmujące się konfekcjonowaniem zabielacza do kawy i kakao. W 1993 roku rozpoczęło produkcję owocowej herbaty rozpuszczalnej, kakao instant, kawy cappuccino oraz czekolady. Rok później rozpoczęto produkcję cukierków. W 1995 do Grupy Maspex dołączyła Polska Żywność S.A. z Olsztynka – producent soków owocowo-warzywnych dla dzieci, m.in. popularnego Kubusia. Cztery lata później do grupy dołączyły Tymbark – producent napojów, soków i przetworów owocowych oraz Anin – producent cappuccino instant i śmietanek do kawy.',932000000,6500,'Wadowice ul. F. Chopina 10','2017-02-21 13:55:06.107457','2017-02-21 13:56:45.549079');
INSERT INTO "companies" VALUES(11,'Grupa Kapitałowa Energa','polska grupa kapitałowa zajmująca się wytwarzaniem, dystrybucją i sprzedażą energii elektrycznej, dostarcza prąd do około 2,7 mln odbiorców, co stanowi ok. 17-procentowy udział w rynku obrotu energii elektrycznej.

Grupa Energa jest trzecim największym operatorem systemu dystrybucyjnego w Polsce pod względem wolumenu dostarczanej energii. Grupa ma ponad 2,9 mln klientów. Sieć dystrybucyjna składa się z linii energetycznych o długości ponad 193 tys. km, obejmuje blisko 77 tys. km kw. – ok. 25 proc. powierzchni kraju.',2674000000,9100,'al. Grunwaldzka 472 Gdańsk','2017-02-21 14:06:18.650999','2017-02-21 14:06:18.650999');
INSERT INTO "companies" VALUES(12,'Faszyzm S.A.','Firma produkująca różnokolorowe koszule, oraz broń wszelkiego gatunku. Inspirowana przez Musoliniego firma jest najczęściej wspominaną przez polityków lewicy działalnością. Ambicje założycieli sięgają ekspansji na cały świat',500,100,'ul. nazistowska 44','2017-02-22 10:01:47.013324','2017-02-22 10:01:47.013324');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('companies',12);
CREATE UNIQUE INDEX "unique_schema_migrations" ON "schema_migrations" ("version");
COMMIT;
